@startuml

actor Customer
participant "OrderSystem" as OS
participant "Inventory" as Inv

database "DB"

Customer -> OS: Оформить заказ
OS -> Inv: Проверить наличие
Inv --> OS: Результат
OS -> DB: Сохранить заказ
DB --> OS: Подтверждение
OS --> Customer: Заказ оформлен

@enduml 