@startuml

actor Customer
actor Admin

rectangle "Магазин видеокарт" {
    usecase "Просмотр каталога"
    usecase "Оформление заказа"
    usecase "Управление товарами"
    usecase "Управление заказами"
}

Customer --> "Просмотр каталога"
Customer --> "Оформление заказа"
Admin --> "Управление товарами"
Admin --> "Управление заказами"

@enduml 